// Built-in Decode Missions phrase bank (kid-friendly school life / D&T / communication).
// Teachers can add their own phrases on the /teacher page.
module.exports = [
  'Meet me at the workshop after lunch',
  'I forgot my homework',
  'Can you help me with my project?',
  'The 3D printer is broken',
  "Let's go to the canteen",
  'I am feeling nervous about the test',
  'I cut my finger, I need a plaster',
  'Please wear your safety goggles',
  'My sketch is finished',
  'The glue gun is too hot',
  'I lost my pencil case',
  'It is raining, bring an umbrella',
  'I am so hungry, is it recess yet?',
  'We won the football match',
  'The laser cutter is ready',
  'My phone battery is dead',
  'I need more cardboard for my model',
  'The teacher is coming, be quiet',
  'I missed the school bus',
  'Happy birthday to you',
  'Let us brainstorm some ideas',
  'My prototype fell apart',
  'Can I borrow your ruler?',
  'The air-con is too cold',
  'I am sleepy after PE',
  'Let us work together as a team',
  'I have a great idea',
  'Do not forget to wash your hands',
  'The wood needs more sanding',
  'I am late for class',
  'We have a test tomorrow',
  'Thank you for helping me',
  'I am sorry, it was an accident',
  'My drawing is upside down',
  'Let us measure twice and cut once',
  'The library is closed today',
  'I feel happy because I passed',
  'Turn off the lights to save energy',
  'Recycle the plastic bottles',
  'I am going home now, bye',
  'The soldering iron is dangerous',
  'Our group presentation is next',
];
